"""initial_schema

Revision ID: 4633eff80bed
Revises: 
Create Date: 2026-06-04 08:56:36.172445

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4633eff80bed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE control_archivos ENGINE=InnoDB")
    op.execute("ALTER TABLE hallazgos ENGINE=InnoDB")
    op.create_table('scan_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_paths', sa.Text(), nullable=False),
    sa.Column('extensions', sa.Text(), nullable=False),
    sa.Column('entities', sa.Text(), nullable=False),
    sa.Column('max_workers', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_configs')),
    mysql_engine='InnoDB'
    )
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('files_total', sa.Integer(), nullable=False),
    sa.Column('files_scanned', sa.Integer(), nullable=False),
    sa.Column('files_skipped', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_jobs')),
    mysql_engine='InnoDB'
    )
    op.alter_column('control_archivos', 'ultima_actualizacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.add_column('hallazgos', sa.Column('scan_job_id', sa.Integer(), nullable=True))
    op.add_column('hallazgos', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('hallazgos', sa.Column('is_sensitive', sa.Boolean(), nullable=True))
    op.add_column('hallazgos', sa.Column('is_resolved', sa.Boolean(), nullable=True))
    op.add_column('hallazgos', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.alter_column('hallazgos', 'fecha_deteccion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_foreign_key(op.f('fk_hallazgos_scan_job_id_scan_jobs'), 'hallazgos', 'scan_jobs', ['scan_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_hallazgos_scan_job_id_scan_jobs'), 'hallazgos', type_='foreignkey')
    op.alter_column('hallazgos', 'fecha_deteccion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('hallazgos', 'resolved_at')
    op.drop_column('hallazgos', 'is_resolved')
    op.drop_column('hallazgos', 'is_sensitive')
    op.drop_column('hallazgos', 'file_name')
    op.drop_column('hallazgos', 'scan_job_id')
    op.alter_column('control_archivos', 'ultima_actualizacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_table('scan_jobs')
    op.drop_table('scan_configs')
    # ### end Alembic commands ###
