"""create_db_configs_table

Revision ID: d78750b0a125
Revises: fbf52d201d96
Create Date: 2026-06-04 16:28:43.644023

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78750b0a125'
down_revision: Union[str, None] = 'fbf52d201d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=191), nullable=False),
    sa.Column('db_type', sa.String(length=50), nullable=False),
    sa.Column('connection_string', sa.Text(), nullable=False),
    sa.Column('tables_to_scan', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_db_configs')),
    sa.UniqueConstraint('name', name=op.f('uq_db_configs_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_configs')
    # ### end Alembic commands ###
