"""add_scheduling_columns

Revision ID: fbf52d201d96
Revises: 4633eff80bed
Create Date: 2026-06-04 10:32:08.346303

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf52d201d96'
down_revision: Union[str, None] = '4633eff80bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_configs', sa.Column('schedule_type', sa.String(length=50), server_default='none', nullable=False))
    op.add_column('scan_configs', sa.Column('schedule_time', sa.String(length=10), server_default='00:00', nullable=False))
    op.add_column('scan_configs', sa.Column('schedule_day', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scan_configs', sa.Column('last_scheduled_run', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_configs', 'last_scheduled_run')
    op.drop_column('scan_configs', 'schedule_day')
    op.drop_column('scan_configs', 'schedule_time')
    op.drop_column('scan_configs', 'schedule_type')
    # ### end Alembic commands ###
